apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phoenix-data
  namespace: observability
  labels:
    app.kubernetes.io/name: phoenix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
